version: '3.8'

services:
  db:
    volumes:
      - /var/lib/mysql
    container_name: halodb
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: halodb
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
      DATABASE_PORT: 3306
