spring:
  datasource:
    url: jdbc:mysql://localhost:3306/halodb?createDatabaseIfNotExist=true
    password: root
    username: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: update
    generate-ddl: true

app:
  security:
    jwt:
      issuer: Halo
      secret: ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789abcdefghijklmnopqrstuvwxyz*!-*/
      access-token:
        expiration: 2
      refresh-token:
        expiration: 5
