spring:
  datasource:
    url: jdbc:mysql://0.0.0.0:3306/halodb?createDatabaseIfNotExist=true
    password: root
    username: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: update
    generate-ddl: true
  profiles:
    active: docker